name: Auto Update VIDIO Channels

on:
  schedule:
    - cron: '0 */3 * * *'  # Otomatis jalan setiap 3 jam sekali nonstop
  workflow_dispatch:        # Tombol manual jika ingin langsung update

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Streamlink
        run: |
          pip install -r requirements.txt

      - name: Jalankan Generator
        run: |
          python generator.py

      - name: Simpan Perubahan ke Tvstream
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Tvstream
          git commit -m "Auto-update siaran VIDIO terbaru [skip ci]" || exit 0
          git push
