name: Auto Update VIDIO Channels

on:
  schedule:
    - cron: '0 */6 * * *'  # Otomatis jalan setiap 6 jam sekali nonstop
  workflow_dispatch:        # Tombol manual jika ingin langsung update

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install requests

      - name: Run Generator
        run: |
          python generator.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Tvstream
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update Vidio channels [skip ci]" && git push)
